#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main()
{
printf("/*\n");
printf("                                    :Zu\n");
printf("                                   iB@B@i                                                                                      iGM;\n");
printf("                                  i@@B@@@B2                                                                                 7B@B@B@.\n");
printf("                                  @@@@B@B@B@u                                                                            iM@B@B@B@BL\n");
printf("                                 B@B@N  OB@@@BY                                                                        F@@@B@BMM@B@O\n");
printf("                                E@B@B    .O@B@B@:                                                                   :BB@@@B@0U7FB@B@\n");
printf("                               :@B@B.      .@B@B@O                                                                YB@B@B@OSYJjuU@B@B\n");
printf("                               @B@B5         rB@B@B7                                                            u@B@B@BNuYj1UFuuB@B@i\n");
printf("                              2@@@@            N@@@@M                                                         5B@B@BBkjYU252511JMB@B1\n");
printf("                              @@B@i             :@@@B@                                                      J@B@@@MFLju515151FUJE@B@M\n");
printf("                             F@B@B                @@@B@,                                                  iB@B@@B1YJ12F152F1511JPB@B@\n");
printf("                             @B@B:                 EB@@@.                            . .::::....         O@@B@BSLuU51F151F15152u2@B@B\n");
printf("                            L@@B@                   0B@B@        .:rLuk8MB@B@B@B@B@B@@@B@B@B@B@@@@@B@B@G@@@B@PuY2251F1F151F1F1Fu2B@B@.\n");
printf("                            B@@@Y                    @B@BB2MB@B@@@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@B@BMujU52F1F151525151511Y@@@Bi\n");
printf("                            @B@B                      @B@@@B@@@B@@@B@@@BBZNuu7ri:,,..        B@B@0kN88MB@BEYu252525151F252F1F15UJM@B@J\n");
printf("                           JB@B@                      0@B@@BE17i,.                           @B@BUvJYJLJjUj125151F152525151F1F55YO@@BX\n");
printf("                           B@B@v                                                            .B@B@jUU5252221212F2515251F15252F1F2JE@B@O\n");
printf("                           @B@B.                                                             @B@BFJF1F2F2F2F2515151F152F251F5515YEB@B@\n");
printf("                          .B@@@                                                              B@B@ELU52F152F251525151515252F1F2F2JX@B@B\n");
printf("                          v@B@B                                                              vB@B@uj255F15151F2F15252515151F1S15JNB@B@\n");
printf("                          PB@BX                                                               @B@BBYu2F1F1F2F15152F2515151F152F1jP@B@B\n");
printf("                          B@B@v                                                                @B@BBjJu5251S25151F15251515151F15JNB@@B\n");
printf("                          BB@@:                                                                 @B@B@XYL2UF151F15151F2F251F2F251j0@B@B\n");
printf("                          B@B@i                                                                  @B@B@BPJJJU251111152525152121Uuv1B@B@B.\n");
printf("                        FB@B@B                                                                    vB@B@B@ZSjjLujUu1U1u2u2uuJJLj2XZ@@@B@@:\n");
printf("                       @B@B@u                                                                       v@@@B@B@MOXkuujuJjJuu55qEMB@@@B@B@B@Bi\n");
printf("                     :@B@B@                                                                           :P@B@B@@@B@B@B@B@B@B@@@B@B@B@U L@B@Bi\n");
printf("                    r@B@BE                                                                               .vO@@B@B@B@B@B@B@B@B@MU:     Y@B@B\n");
printf("                   r@B@Bu                                                                                      ,rL52F15Uv;:            k@B@B\n");
printf("                  ,@@@BJ                                                          :BB1                                                  B@B@M\n");
printf("      .           @B@BP                               .5X,                        @B@B@Bv                                                B@B@:\n");
printf("    r@B@@@@Mu:   BB@B@                               .B@B@                        .8B@B@B@BF,                                            uB@B@\n");
printf("    7B@B@B@@@B@B8B@@@                               7B@B@M                           iMB@B@@@B@Xr.                                        @B@B:\n");
printf("      .:iJZ@B@B@B@@@k                            :5@B@B@X                               ,SB@B@B@B@B@BPYi..                                P@B@Z\n");
printf("             .rB@B@B@BMi             r@BONE0EM@B@B@B@B@:                                    i5@B@@@B@B@B@@@B@                             :B@B@\n");
printf("               @B@B@B@B@O            @B@B@B@@@@@B@@@5.                                           :LEB@B@B@B@B:                             @B@B\n");
printf("              iB@B@ iB@B7            :ZM@B@B@BO57,                                                       .:i                               B@B@ii2OOk\n");
printf("              M@B@2                                                                                                                        @B@B@B@B@@@\n");
printf("              @B@B.                                                                   .jOM07                                           .UB@B@B@B@@@B@r\n");
printf("             .B@B@                                                                   MB@B@@@B7                                        M@B@B@B@Bi\n");
printf("             r@B@B                                7O@@BJ                            SB@B@B@B@B.                                       PB@BP@@B@\n");
printf("             uB@BO                               @@@B@B@Br                          8@@@B@B@B@:                                            @B@B\n");
printf("             S@@@F                              @B@B@B@B@@                          .B@B@B@B@B                                            ZB@Bk\n");
printf("             SB@B1                              B@B@B@B@@@                            5@B@B@7                                             B@B@.\n");
printf("             v@B@k                              .B@@@@@B@r                                                                               2@B@B\n");
printf("             vB@B@:r7;                            vBB@BF                                                                                 @B@B:\n");
printf("    :71Z@B@B@B@B@B@B@BM                                                                                                                 8B@BE\n");
printf("v@B@B@B@@@B@B@@@B@B@B@r                                                                                                            @B@B@B@@@:\n");
printf("@B@B@B@BMFJi: MB@BJ                                                                                                               .B@B@B@B@@@B@Ov\n");
printf(" .7:          :@B@@                                                                                                                  ;@@B@B@B@B@@@@2\n");
printf("               B@B@v                                                                                                                 Z@@@B  ,LMB@B@B@r\n");
printf("               rB@B@                                                                                                                B@B@B       .EB@B@\n");
printf("                @B@BM                                                                                                             .B@B@B          .M@j\n");
printf("                 @B@B1                                                                                                           rB@@@M\n");
printf("                 :@B@Bj                                              i8B@B@B@B@B@Bu                                             GB@B@F\n");
printf("                  i@B@BX                                            M@@@B@@@B@B@B@B@                                          :@@@B@i\n");
printf("                   i@B@B@                                           7B@BFri:,:ivOB@X                                        ,B@B@BM\n");
printf("                    .@B@B@L                                                                                               ,BB@@@Bi\n");
printf("                      qB@B@@7                                                                                           jB@B@B@L\n");
printf("                       :B@B@B@2.                                                                                     JB@@@B@Bv\n");
printf("                         :@B@B@B@u.                                                                              ,FB@B@B@BP,\n");
printf("                           .S@B@B@B@0r                                                                       :jBB@B@B@@@B.\n");
printf("                              :P@B@B@B@BOv,                                                          .:7kO@B@B@B@@@B@B@@@\n");
printf("                                 .vBB@B@B@@@B@ONjr:,                                       ,:rYXE@B@@@@@@@B@@@B@MEuri@@@B.\n");
printf("                                     J@B@B@B@B@B@@@@@B@B@B@@BM8ENFPFUuUuuuU5XFP0GOMB@B@B@B@B@@@B@B@B@B@B@BMX2vr::::,iB@B@\n");
printf("                                     rB@BM71NMB@B@B@@@B@@@@@B@B@B@B@B@@@B@@@B@@@B@B@B@B@@@B@@@B@BBZqULri:::::::;;rr:r@B@B.\n");
printf("                                     u@B@E.,::::iirvLJFFN0OOMM@B@BMO@B@B@@@B@B@@@@@B@MuL2JY77ii:::::::ii;irrrr7r7rr:iB@B@.\n");
printf("                                     1B@BZ,;rr;;ii:i::::::::::::,.:Z@@B@B@quLYJqB@B@B@q: ::::ii;;rrrr7rrr7r7rrii::::u@B@B.\n");
printf("                                     F@@@P.::i;rrrrrrrrrr;r;r;ri,7@@@@@u.         L@@B@BL,rr7r7r7r7rrrrrrii::::iLSBB@B@B@:\n");
printf("                                     OB@B@EF7;::,::ii;ir;rrrrr;:7@B@BO   .....      N@@@BL:rrrrri;ii:::::irLF8B@B@B@B@B@Bv\n");
printf("                                     Z@B@@@B@B@MZ5J7ri:::,:::::,@B@@E  .,,:,,..      N@B@B,.:::::i;7j2NO@B@B@B@B@B@E:F@B@P\n");
printf("                                     @B@BBB@@@B@B@B@@@B@MOqX1u7UB@B@  .:,,,,..  ,.    B@B@k1NOM@B@B@@@B@B@B@B@BSi    iB@B@\n");
printf("                                    iB@B@   iYG@@@@B@@@B@B@@@B@B@B@M  ,,:,,., rB@B@5. ZB@B@B@B@@@B@@@B@BBF7,          @B@B\n");
printf("                                    B@B@u          :rjSO@@B@B@B@B@B@  .,,,.,. r@@@@@B8M@B@B@B@BOFu;:.                 B@B@i\n");
printf("                                   S@B@B                        @B@@r  .......  :5@B@B@B@B                            5B@BB\n");
printf("                                  L@@@B,                        7@B@Bi   . . .     .B@B@Bu                             @B@@.\n");
printf("                                 G@B@B;                          q@B@Bk            7@B@BM                              G@B@@\n");
printf("                                B@B@B:                            L@B@B@O7.    .rOB@B@Bu                                B@B@B\n");
printf("                                qB@M                                ZB@B@@@B@@@B@B@B@Z                                  .B@@@B\n");
printf("                                                                      7MB@B@B@B@B@Mv                                      S@8.\n");
printf("                                                                          ,:7ri.\n");
printf("\n");
printf("\n");
printf("                         ...                    .                                     ..        ..\n");
printf("                  :7FB2  B@B   r.              :@B.                                  L@@        @B                      ,.,.,..\n");
printf("         .@@@@B@B@B@@@B  OB@  L@BO             j@@      B@B@B@B@B@B@@@B@     0PXSXSSJMB@L5FXSSuNB@u5SXSXXZi     ,,,,., iB@B@@@@ B@B@B@B@@@B@M\n");
printf("          @BOurE@B       F@B    M@@M:          O@i      :::,:,,..  :@B@O     @@@@B@@@B@B@B@B@B@@@B@B@@@B@B2     @B@B@B .@E  .B@ .,,.... @BL..\n");
printf("               rBB       rB@      B@Y      vEFL@BNuF2uj           u@BX               .B5        F5              B@  B@  BE  O@.         q@\n");
printf("               v@B       :@@               E@B@B@B@B@@@         XB@P           k1jujjSMG0qPqMB@BBB@B@B@v        @B  B@  @0  @B  iLUUuY. ZB,\n");
printf("         @B@B@B@B@B@B@@@B@B@B@B@B@B@B@B       L@u   .@B        @@@             @B@B@BBOMOM@E2PXqkLi:vi,.        @@  B@  Bq 0B,  B@@@@@Y N@:\n");
printf("         ii::,.S@B .:,:,.:@@i.::,.   ,i       @B.   JBq        0@1               iJ      r@Y        @@          @B  @B  @1 B@   MB  .B7 NB:\n");
printf("               7B@        @@      :@7        :@@    B@i.:::::: MBO ,::::i        MB@      B@O     E@B7          B@  B@  Bk @B:  O@  ,@r k@,\n");
printf("               r@M    r5  @Bu    5@Bk        M@v    @B B@B@B@B@B@@@B@B@B@:        5B@.     BE   r@@F            @B  @B  @E  @B  OB. :B7 PB:\n");
printf("             ,:MB@B@B@B@. U@B  .@@@.        .@B    PB8         E@q                 ;i     .O;    J              B@  B@  B8  :@q E@  .@r k@,\n");
printf("         B@B@@@B@BPu7,     B@ uB@5           v@@S  B@          E@E           UEkk5277J1YvrBB@r7LYrLUFFkkqE:     @B  MB  @Z   B@ PBi YBv NB:\n");
printf("         0Mui. LBB         MB@BB               7B@B@:          OBO           @B@B@B@B@O@B@B@B@B@O@B@B@@@B@;     @@  @@ .@0   @B P@B@B@v N@:\n");
printf("               v@B        qB@Br     iXi          B@BP          8@O                    7@@ iBX @Bi               @B@B@B  @B7v@BG @B:     OB:\n");
printf("               JB@     JB@B51@B     M@@        LB@:rB@Bi       GBM                 ,B@BL  r@8  vB@8,           .@@  5@ .@Gq@Bv   ,      Z@:\n");
printf("               L@B  PB@B@J   M@B.   @@7      i@B@    0@7       B@M              iO@@@r    YBB    r@B@BY.        :.     :@q              MB:\n");
printf("          G@N5S@BB  Z@S.      P@BZ.uB@     ,B@B7         UB@B@@@B:           OB@@@5       j@B       L@B@B@,            iBB         FMq1OB@\n");
printf("          2B@B@MJ              :@B@B@:      Sj            NFXF5i             ,@u          qB@          .Y.             i@O         Y@B@BZ.\n");
printf("                                  ..                                                      :Ur\n");
printf("\n");
printf("\n");
printf("\n");
printf("                           k   :..,,       r  ii      v:   ir .L         E         ..,,:,iivv    :..   ,F      :  u   .:iu1\n");
printf("                        .u5BjL:i@@rB@     @k  :Bi    7@Bu. uMiNBuL ,@SSuEB5qZUO8  :qN1uM@7777:  :v@B i2X@vS@   Bv @ 7B7v7i:\n");
printf("                          .@   ,B  UB   v@:     BX   Li O O7u 2 O.  28 .Br,S :B.  r7vvrE@7vjLL   :B  Yiv@:7@j  BqiB 7B\n");
printf("                        :LuB27i8  uG  .B@r..:ii,,F@: JO1@ 0;F B7@:   Lr rOui k.    M1::2@:ii@   ,BqF  i7@,78   ON.. rB@Y7Z@\n");
printf("                         2 @r  NY55E:    r:@B77rBr   :2@.v1ik .@.,  uM ,OG:Bq Br   @5::2@,:iB,  ,, @ :;vBiii   @8ir vJY7 Mu\n");
printf("                         B 8E7 B   0O     .@    @i   :@B7  Mi 5B5: .P: i,BF j i2   5Yi:F@:ii8   .B7G 77J@rvJ:  B7 @ P7 BPG\n");
printf("                        :@k@.  @v7rO7    2B     B     B,  i@   @   iJujLr@G77uJU  .7r7iNBi;7rr   uBL :.:B  .. .@  B B  BBJ\n");
printf("                        @i 1ZXqkEq0X0  7@P  qk0B5    BE  7@    B         B7       ZXF2U8@j11k0r YB.rSuuuGjUkX 1P  @PXv@i X@:\n");
printf("\n");
printf("I am so vegetable.\n");
printf("*/\n");

    return 0;
}


